### ISSUE TITLE
Question about obtain latent vector from random image

### ISSUE THREAD

**Issue by triton99** [bihamta/emostyle#2]
Hi @bihamta , Thanks for sharing this great work!

I want to use your code to edit the emotion of my image, but first, we need to get the latent vector from the image. I got it by running the invert.py with checkpoint ffhq.pkl . However, the inverted image generated from the code script looks different from the original image.

The original image:
<img src="https://github.com/bihamta/emostyle/assets/53249939/1aff7b7c-f78d-4a78-a6fa-59daf2c0e3b0" width="40%" height="40%">

The inverted image generates from invert.py:
<img src="https://github.com/bihamta/emostyle/assets/53249939/1d666726-fbac-4207-b002-5d37d9d26a17" width="40%" height="40%">

 I used the generated latent for test.py scripts (with pretrained ffhq.pkl and emo_mapping_wplus_2.pt) and got different appearance results from the original (the emotion changed).
![res_imgresult_face_2](https://github.com/bihamta/emostyle/assets/53249939/7128394b-17fd-4031-a729-8a74035ff820)

Could you give some advice for fixing these problems? Thank you.

**Comment by bihamta** [comment]
Hi, for training your personalized version of EmoStyle please use the `"train_personalized.py"` file and then run `test.py`. Make sure to replace the StyleGAN checkpoint with your new checkpoint, which is the finetuned version of StyleGAN on your images.
The "ITER_NUM" parameter is initially set to 500. You can adjust this value if you're finetuning StyleGAN on only one image.

**Comment by triton99** [comment]
Hi @bihamta ,

I tried the personalized track and used 1 image of a person cropped the faces (upsize 256x256, 512x512, 1024x1024 from DeepFashion dataset), 100/500/1000 iterations. However, the results have artifacts and still do not show the inside appearance of the faces.

The original image (133x134):

![cropped_1](https://github.com/bihamta/emostyle/assets/53249939/7389f3b2-e048-4ef6-afba-5ebc46612895)

The result of 500 iterations with 1024x1024 resolution:

![res_imgresult_cropped_1024_1_finetune_oneimg](https://github.com/bihamta/emostyle/assets/53249939/8fc2a280-0d1c-47ce-a86c-deb91f11c4b9)

The result of 1000 iterations with 1024x1024 resolution:

![res_imgresult_cropped_1024_1_finetune_oneimg_1000](https://github.com/bihamta/emostyle/assets/53249939/34c5b2ba-c62a-4aad-af47-e1f9ac15726d)

The result of 500 iterations with 512x512 resolution:

![res_imgresult_cropped_512_1_finetune_oneimg](https://github.com/bihamta/emostyle/assets/53249939/fc1d1455-5afb-4868-a9e4-89c34ee7eb38)

The result of 500 iterations with 256x256 resolution:

![res_imgresult_cropped_256_1_finetune_oneimg](https://github.com/bihamta/emostyle/assets/53249939/2848664c-495a-4ee1-8965-243f1a7029ed)

Other results of 500 iterations with 1024x1024 resolution fine-tune 1 image:

![res_imgresult_cropped_1024_3_finetune_oneimg](https://github.com/bihamta/emostyle/assets/53249939/12e27926-655f-4d42-ab19-c04245efb77c)

![res_imgresult_cropped_1024_4_finetune_oneimg](https://github.com/bihamta/emostyle/assets/53249939/6ccc25ca-b32d-43e1-baed-f5addac1e379)

![res_imgresult_cropped_1024_10_finetune_oneimg](https://github.com/bihamta/emostyle/assets/53249939/2ec13962-3de7-4a28-8f23-ecbc0c508fbc)

I tried the Obama image and it worked well. Does it have any requirements or recommendations for getting feasible results?

Thank you
